name: Pytest app

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test: 
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: True
      matrix:
        python-version: ["3.7", "3.8"]

    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install
        run: |
          pip install -e .
          pip install -r requirements.txt

      - name: Run tests
        run: pytest